# Generated by Django 6.0.5 on 2026-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadProgramada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=255)),
                (
                    "requiere_preregistro",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Preregistro"
                    ),
                ),
                (
                    "minutos_anticipacion_cierre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de minutos antes del inicio del evento en las que se cerrará el preregistro.",
                        verbose_name="Minutos previos para cierre",
                    ),
                ),
                ("permite_qr_invertido", models.BooleanField(default=False)),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("fecha_hora_fin", models.DateTimeField()),
                (
                    "lugar_desarrollo",
                    models.CharField(
                        max_length=255, verbose_name="Lugar de Desarrollo"
                    ),
                ),
                (
                    "pin_confirmacion",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="PIN de Validación",
                    ),
                ),
                (
                    "confirmacion_asistencia_temporal",
                    models.BooleanField(default=False),
                ),
                (
                    "minutos_duracion_enlace",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minutos que durará activo el QR desde el inicio del evento",
                        null=True,
                    ),
                ),
                ("aplicar_evaluacion", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_confirmacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Solo Registrado"),
                            ("CONFIRMADO", "Presencia Confirmada"),
                        ],
                        default="REGISTRADO",
                        max_length=15,
                    ),
                ),
                (
                    "codigo_pase_unico",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("evaluacion_completada", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Control de Asistencia",
                "verbose_name_plural": "Controles de Asistencia",
            },
        ),
    ]
