# Generated by Django 6.0.5 on 2026-06-27 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EstructuraApp", "0001_initial"),
        ("Eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadprogramada",
            name="id_responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="actividadprogramada",
            name="id_tipo_actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_programadas",
                to="EstructuraApp.tipoactividad",
                verbose_name="Tipo de Actividad",
            ),
        ),
        migrations.AddField(
            model_name="registroasistencia",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="Eventos.actividadprogramada",
            ),
        ),
        migrations.AddField(
            model_name="registroasistencia",
            name="asistente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_actividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registroasistencia",
            unique_together={("actividad", "asistente")},
        ),
    ]
