# Generated by Django 6.0.5 on 2026-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventos", "0004_alter_actividadprogramada_id_responsable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadprogramada",
            name="requiere_preregistro",
            field=models.BooleanField(
                default=False, verbose_name="Requiere Preregistro"
            ),
        ),
    ]
