# Generated by Django 6.0.5 on 2026-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventos", "0005_alter_actividadprogramada_requiere_preregistro"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="organizacion_origen",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Empresa/Dependencia",
            ),
        ),
        migrations.AddField(
            model_name="registroasistencia",
            name="seudonimo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seudónimo"
            ),
        ),
    ]
