# Generated by Django 6.0.5 on 2026-06-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PersonasApp", "0002_cargar_maestros_y_permisos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="roles",
        ),
        migrations.DeleteModel(
            name="PersonaRol",
        ),
        migrations.DeleteModel(
            name="Rol",
        ),
    ]
