# Generated by Django 6.0.5 on 2026-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PersonasApp", "0002_cargar_maestros_y_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="autoriza_datos",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la persona autoriza el tratamiento de sus datos personales",
                verbose_name="Autoriza tratamiento de datos",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_autoriza",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se otorgó la autorización",
                null=True,
                verbose_name="Fecha de autorización",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="ip_autoriza",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Dirección IP desde la que se otorgó la autorización",
                null=True,
                verbose_name="IP de autorización",
            ),
        ),
    ]
