# Generated by Django 6.0.5 on 2026-08-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PersonasApp", "0003_persona_autoriza_datos_persona_fecha_autoriza_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="organizacion_origen",
        ),
    ]
