# Generated by Django 6.0.5 on 2026-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Encuesta de Satisfacción", max_length=200
                    ),
                ),
                ("activa", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("escala_maxima", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaAnonima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de respuesta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Anónima",
                "verbose_name_plural": "Respuestas Anónimas",
            },
        ),
    ]
