# Generated by Django 6.0.5 on 2026-06-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EvaluacionesApp", "0001_initial"),
        ("Eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="actividad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluacion",
                to="Eventos.actividadprogramada",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="EvaluacionesApp.evaluacion",
            ),
        ),
        migrations.AddField(
            model_name="opcionrespuesta",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="EvaluacionesApp.pregunta",
            ),
        ),
        migrations.AddField(
            model_name="respuestaanonima",
            name="opcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="EvaluacionesApp.opcionrespuesta",
            ),
        ),
        migrations.AddField(
            model_name="respuestaanonima",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="EvaluacionesApp.pregunta",
            ),
        ),
    ]
