# Generated by Django 6.0.5 on 2026-06-29 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvaluacionesApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="escala_maxima",
            field=models.PositiveIntegerField(
                default=2, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
    ]
