# Generated by Django 6.0.5 on 2026-07-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EvaluacionesApp", "0003_alter_pregunta_escala_maxima"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComentarioAnonimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="EvaluacionesApp.evaluacion",
                    ),
                ),
            ],
        ),
    ]
