# Generated by Django 6.0.5 on 2026-06-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objetivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_objetivo", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Objetivo",
                "verbose_name_plural": "Objetivos",
            },
        ),
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_organizacion", models.CharField(max_length=255, unique=True)),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logo de la Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
            },
        ),
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_linea", models.CharField(max_length=255)),
                (
                    "id_objetivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas",
                        to="EstructuraApp.objetivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("Presencial", "Presencial"),
                            ("Virtual", "Virtual"),
                            ("Otro", "Otro"),
                        ],
                        default="Presencial",
                        max_length=20,
                    ),
                ),
                (
                    "id_linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_actividad",
                        to="EstructuraApp.linea",
                        verbose_name="Línea de Acción",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_unidad", models.CharField(max_length=255)),
                (
                    "id_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to="EstructuraApp.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad",
                "verbose_name_plural": "Unidades",
            },
        ),
        migrations.AddField(
            model_name="objetivo",
            name="id_unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objetivos",
                to="EstructuraApp.unidad",
            ),
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cargo", models.CharField(max_length=255)),
                (
                    "id_unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="EstructuraApp.unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
    ]
