# Generated by Django 6.0.5 on 2026-07-12 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EstructuraApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="limite_eventos_mes",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Límite de eventos por mes",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="plan",
            field=models.CharField(
                choices=[
                    ("BASICO", "Plan Básico - Solo eventos abiertos"),
                    ("PRO", "Plan Pro - Pre-registro + Evaluaciones"),
                    ("ENTERPRISE", "Plan Enterprise - Pase Digital QR + Todo"),
                ],
                default="BASICO",
                max_length=20,
                verbose_name="Plan de suscripción",
            ),
        ),
    ]
