# Generated by Django 6.0.5 on 2026-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EstructuraApp", "0002_organizacion_limite_eventos_mes_organizacion_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="correo_tratamiento_datos",
            field=models.EmailField(
                blank=True,
                help_text="Dirección de correo para consultas sobre tratamiento de datos personales",
                max_length=254,
                null=True,
                verbose_name="Correo para tratamiento de datos",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="texto_consentimiento",
            field=models.TextField(
                blank=True,
                default="Al registrarme, autorizo de manera expresa, libre e informada a f'{self.nombre_organizacion}' y a su proveedor tecnológico \n        Qdata Technologies SAS (Propietario de ASISTO), para el tratamiento de mis datos personales aquí consignados, con la finalidad de gestionar mi \n        participación en sus eventos, control de aforo, envío de memorias y evaluaciones de satisfacción. Conozco que puedo ejercer mis derechos de acceso, \n        rectificación y supresión a través del correo f'{self.correo_tratamiento_datos}'.",
                help_text="Texto que se mostrará para solicitar el consentimiento de tratamiento de datos",
                verbose_name="Texto de Consentimiento",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="url_politica_datos",
            field=models.URLField(
                blank=True,
                help_text="Enlace a la política de privacidad y tratamiento de datos",
                null=True,
                verbose_name="URL Política de Datos",
            ),
        ),
    ]
